public enum SoundEnum
{
    JeromMusicBot,
    BetClosed,
    Wave,
    PublicYeah,
    PublicWow,
    PublicBouh,
    PublicGogogo,
    PublicBordel,
    CelebratingYummy,
    CelebratingAmazing,
    CelebratingByeBye,
    CelebratingChadWin,
    Countdown,
    ChadTheme,
    Validating,
    ChadTransfo
}